// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtBtG6CTCZYMxXmFpA3239hbAcF4A-AzU',
    appId: '1:1004526607684:web:73cef7c6eb9340fddc4b11',
    messagingSenderId: '1004526607684',
    projectId: 'ball-killer',
    authDomain: 'ball-killer.firebaseapp.com',
    storageBucket: 'ball-killer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFWUdEtgWuJInkcd1dkjIYmSUxla3NFw',
    appId: '1:1004526607684:android:933df48a6e833c5edc4b11',
    messagingSenderId: '1004526607684',
    projectId: 'ball-killer',
    storageBucket: 'ball-killer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRTJ7m_GXYLHu8lpPTQIjfh1aaPK_Fps',
    appId: '1:1004526607684:ios:8bed6e49e9a12343dc4b11',
    messagingSenderId: '1004526607684',
    projectId: 'ball-killer',
    storageBucket: 'ball-killer.firebasestorage.app',
    iosBundleId: 'com.example.ballKiller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbRTJ7m_GXYLHu8lpPTQIjfh1aaPK_Fps',
    appId: '1:1004526607684:ios:8bed6e49e9a12343dc4b11',
    messagingSenderId: '1004526607684',
    projectId: 'ball-killer',
    storageBucket: 'ball-killer.firebasestorage.app',
    iosBundleId: 'com.example.ballKiller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtBtG6CTCZYMxXmFpA3239hbAcF4A-AzU',
    appId: '1:1004526607684:web:0884f9d93586b5c4dc4b11',
    messagingSenderId: '1004526607684',
    projectId: 'ball-killer',
    authDomain: 'ball-killer.firebaseapp.com',
    storageBucket: 'ball-killer.firebasestorage.app',
  );
}
